In [22]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Load the dataset
bank_reviews = pd.read_excel(r"C:\Users\shris\Desktop\Final.xlsx", sheet_name='Final_Sheet')
# Remove NaN values from the data
bank_reviews.dropna(subset=['Comments'], inplace=True)
# Extract comments and sentiment
X = bank_reviews['Comments'].astype(str)
y = bank_reviews['Sentiment']

# Feature engineering
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Naive Bayes ML model
clf = MultinomialNB()

# Hyperparameter tuning
params = {'alpha': np.linspace(0.1,0,1)}
grid_search = GridSearchCV(clf, params, cv=10)
grid_search.fit(X_train, y_train)
clf = grid_search.best_estimator_

# Regularization
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Evaluation
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test, y_pred))
print('Classification Report: \n', classification_report(y_test, y_pred))

C:\Users\shris\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


Accuracy:  0.6871544023819651
Confusion Matrix: 
 [[1463  513  138    2    1    1]
 [ 347  942  426    1    6    1]
 [  23   11  826    1    0    0]
 [   0    0    0    0    0    0]
 [   0    0    0    0    0    0]
 [   0    0    0    0    0    0]]
Classification Report: 
               precision    recall  f1-score   support

    Negative       0.80      0.69      0.74      2118
     Neutral       0.64      0.55      0.59      1723
    Positive       0.59      0.96      0.73       861
    negative       0.00      0.00      0.00         0
         neu       0.00      0.00      0.00         0
           p       0.00      0.00      0.00         0

    accuracy                           0.69      4702
   macro avg       0.34      0.37      0.34      4702
weighted avg       0.70      0.69      0.68      4702



C:\Users\shris\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\shris\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\shris\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
